services:
  db:
    image: postgres:18
    container_name: erp_db
    restart: always
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./certs:/var/lib/postgresql/certs:ro   # ← монтуємо сертифікати
    networks:
      - erp_network
    command: >
      postgres -c ssl=on
               -c ssl_cert_file=/var/lib/postgresql/certs/server.crt
               -c ssl_key_file=/var/lib/postgresql/certs/server.key

  backend:
    build: .
    container_name: erp_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    volumes:
      - .:/app
    networks:
      - erp_network

volumes:
  db_data:

networks:
  erp_network:
    driver: bridge